In [9]:
from typing import Tuple, List
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import helpers
def k_fold_indices(num_examples: int, k: int = 4) -> List[Tuple[np.ndarray, np.ndarray]]:
    """Generates indices for k-fold cross-validation

    Args:
        num_examples: Number of training examples
        k: Number of folds

    Returns:
        List of tuples containing the training indices and validation indices

    """
    indices = np.arange(num_examples)
    split_size = num_examples // k
    val_indices = [indices[k * split_size : (k + 1) * split_size] for k in range(k)]
    both_indices = [(np.delete(indices, val_ind), val_ind) for val_ind in val_indices]
    return both_indices

# Example usage
for train_index, val_index in k_fold_indices(num_examples=8, k=4):
    # Do something with the indices
    print(f"{train_index} {val_index}\n")
print(len(k_fold_indices(num_examples=8, k=4)))

for train_index, val_index in k_fold_indices(len(y), k):
        print(train_index,val_index)
        X0=X_train_sonar[train_index]
        X1=X_test_sonar[val_index]
        y0=y_train_sonar[train_index]
        y1=y_test_sonar[val_index]

        w, _ = train_penalized_logistic_regression(X0, y0, lambd, max_iters, lr, loss_freq)
        
        y_hat = logistic_output(X0, w)
        acc = accuracy(convert_onehot_to_class(y_train_sonar), classify(y_hat))
        print(f'Train accuracy: {100*acc:.2f}%')

[2 3 4 5 6 7] [0 1]

[0 1 4 5 6 7] [2 3]

[0 1 2 3 6 7] [4 5]

[0 1 2 3 4 5] [6 7]

4
