In [12]:
import numpy as np

# Create a 2D array, which will be used in the following cells, an print it out.
x = np.arange(1, 31).reshape((5, 6))
print(f'Array x:\n{x}\n')

### Creating the mask manually.
# Create a mask corresponding to the red squares.
mask = np.zeros((5, 6), dtype=bool)
mask[0, 1:4] = True
mask[2, 2] = True
mask[3, :2] = True
mask[-1, -2:] = True
print(f'mask:\n{mask}\n')

# Select the values using a mask
red = x[mask]
print(f'red:\n{red}\n')

# Combining traditional indexing/slicing and masking - select the green
# columns. Not that the mask is a 1D array whose size is the
# same as the size of the corresponding dimension of the original 
# array `x`.
mask = np.array([True, False, False, False, False, True])
green = x[:, mask]
print(f'green:\n{green}\n')

### Creating the mask using comparison operators.

# Extract the values larger than 26.
mask = x > 26
sel = x[mask]
print(f'mask:\n{mask}\n')
print(f'bigger than 26:\n{sel}\n')

# Extract the odd values.
mask = (x % 2) == 1
sel = x[mask]
print(f'mask:\n{mask}\n')
print(f'odd:\n{sel}\n')

b=np.arange(1, 5).reshape((2, 2))
print(b)

Array x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

mask:
[[False  True  True  True False False]
 [False False False False False False]
 [False False  True False False False]
 [ True  True False False False False]
 [False False False False  True  True]]

red:
[ 2  3  4 15 19 20 29 30]

green:
[[ 1  6]
 [ 7 12]
 [13 18]
 [19 24]
 [25 30]]

mask:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False  True  True  True  True]]

bigger than 26:
[27 28 29 30]

mask:
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]

odd:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]

[[1 2]
 [3 4]]


AttributeError: 'numpy.ndarray' object has no attribute 'zeros'