In [5]:
import numpy as np

## Create a 1D array of 10 elements of type float32 filled with a value 3.14.
## Hint: Use np.ones or np.full.

array_pi = np.array([3.14]*10,dtype=np.float32)  # <<< YOUR CODE HERE
print(f'array_pi:\n{array_pi}\n')

## Find number of elements in the following array without using `size` property.
## Hint: Use np.prod.
x = np.zeros((4, 5, 6, 7, 8))
num_elements = 1  # <<< YOUR CODE HERE
for i in x.shape:
    num_elements*=i
    
print(f'Number of elements in x: {num_elements}')

x_unknown = np.zeros(np.random.randint(1, 5, 6))

x_flat = x_unknown.reshape(-1)  # <<< YOUR CODE HERE
print(f'Shape of x_flat: {x_flat.shape}')

# Check the answers:
assert(array_pi.shape == (10, ) and array_pi.dtype == np.float32 and np.allclose(array_pi, 3.14))
assert(num_elements == x.size)
assert(x_flat.ndim == 1)

# Create a 2D array and print it out.
x = np.arange(1, 31).reshape((5, 6))
print(f'Array x:\n{x}\n')

# Select the subarrays
red=np.arange(1, 11).reshape((5, 2))
red=x[:,::5]
print(f'red:\n{red}\n')

green=np.arange(1, 4).reshape((1, 3))
green=x[2,2:5]
print(f'green:\n{green}\n')

blue=np.arange(1, 7).reshape((3, 2))
blue=x[::2,1:3]
print(f'blue:\n{blue}\n')

# Bonus: Come up with indexing which selects from x the following submatrix:
# [[29, 28], 
#  [11, 10]].

bonus=np.arange(1, 5).reshape((2, 2))
bonus=x[-1::-3,-2:-4:-1]
print(f'bonus:\n{bonus}\n')

# Check the results:
assert(np.allclose(red, np.array([[1, 6], [7, 12], [13, 18], [19, 24], [25, 30]])))
assert(np.allclose(green, np.array([15, 16, 17])))
assert(np.allclose(blue, np.array([[2, 3], [14, 15], [26, 27]])))
assert(np.allclose(bonus, np.array([[29, 28], [11, 10]])))

## Create a 3D array of increasing sequence of even numbers (starting from 0) of shape (10, 5, 7).

x = np.arange(0,700,2).reshape((10,5,7))  # <<< YOUR CODE HERE
print(f'x:\n{x}\n')

## Split the array into 5 arrays each of the shape (2, 5, 7)

splits_5 = np.split(x,5)  # <<< YOUR CODE HERE

## Split the array into 2 arrays of shapes (10, 2, 7) and (10, 3, 7)

splits_2 = np.split(x,[3],axis=1)  # <<< YOUR CODE HERE

# Check the answers.
assert((np.unique(x).size == 10 * 5 * 7) and np.all(x % 2 == 0) and np.min(x) == 0 and np.max(x) == 698)
assert(len(splits_5) == 5 and np.allclose(np.concatenate(splits_5, axis=0), x))
assert(len(splits_2) == 2 and np.allclose(np.concatenate(splits_2, axis=1), x))

array_pi:
[3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14 3.14]

Number of elements in x: 6720
Shape of x_flat: (576,)
Array x:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

red:
[[ 1  6]
 [ 7 12]
 [13 18]
 [19 24]
 [25 30]]

green:
[15 16 17]

blue:
[[ 2  3]
 [14 15]
 [26 27]]

bonus:
[[29 28]
 [11 10]]

x:
[[[  0   2   4   6   8  10  12]
  [ 14  16  18  20  22  24  26]
  [ 28  30  32  34  36  38  40]
  [ 42  44  46  48  50  52  54]
  [ 56  58  60  62  64  66  68]]

 [[ 70  72  74  76  78  80  82]
  [ 84  86  88  90  92  94  96]
  [ 98 100 102 104 106 108 110]
  [112 114 116 118 120 122 124]
  [126 128 130 132 134 136 138]]

 [[140 142 144 146 148 150 152]
  [154 156 158 160 162 164 166]
  [168 170 172 174 176 178 180]
  [182 184 186 188 190 192 194]
  [196 198 200 202 204 206 208]]

 [[210 212 214 216 218 220 222]
  [224 226 228 230 232 234 236]
  [238 240 242 244 246 248 250]
  [252 254 256 258 260 262 264]
  [266 268 270 27